<?php
/**
 * Professional CV Template
 */
$user = wp_get_current_user();
?>
<div id="jobs-cv-print-template" style="display:none;">
	<div class="cv-container" style="font-family: 'Rubik', sans-serif; padding: 40px; color: #333; max-width: 800px; margin: auto; border: 1px solid #eee;">
		<div class="cv-header" style="text-align: center; border-bottom: 3px solid #1d3469; padding-bottom: 30px;">
			<h1 style="color: #1d3469; margin: 0; font-size: 32px; text-transform: uppercase;"><?php echo esc_html( $user->display_name ); ?></h1>
			<p style="margin: 10px 0;"><?php echo esc_html( $user->user_email ); ?></p>
		</div>
		<div class="cv-body" style="margin-top: 40px;">
			<section style="margin-bottom: 30px;">
				<h2 style="color: #1d3469; border-bottom: 2px solid #f0f2f5; padding-bottom: 5px;"><?php _e( 'Professional Profile', 'jobs' ); ?></h2>
				<div style="line-height: 1.8; color: #555;">
					<?php echo wpautop( get_user_meta( $user->ID, 'description', true ) ?: __( 'No summary provided.', 'jobs' ) ); ?>
				</div>
			</section>

			<section style="margin-bottom: 30px;">
				<h2 style="color: #1d3469; border-bottom: 2px solid #f0f2f5; padding-bottom: 5px;"><?php _e( 'Core Competencies', 'jobs' ); ?></h2>
				<p style="color: #555;"><?php _e( 'Detail oriented, highly motivated professional with extensive experience in the field.', 'jobs' ); ?></p>
			</section>
		</div>
		<div class="cv-footer" style="margin-top: 50px; font-size: 12px; text-align: center; color: #999;">
			<p><?php _e( 'Generated by Jobedia Jobs System', 'jobs' ); ?></p>
		</div>
	</div>
</div>

<script>
window.onload = function() {
	var cv = document.getElementById('jobs-cv-print-template').innerHTML;
	var printWindow = window.open('', '', 'height=600,width=800');
	printWindow.document.write('<html><head><title>CV - <?php echo $user->display_name; ?></title>');
	printWindow.document.write('<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap">');
	printWindow.document.write('</head><body>');
	printWindow.document.write(cv);
	printWindow.document.write('</body></html>');
	printWindow.document.close();
	printWindow.print();
};
</script>
